# Site settings
title: Sanda Porfolio
email: 2ezsandaezreal@gmail.com
description: Van Anthony S. Valencia
baseurl: "/Anthony-Porfolio/"
url: ""
twitter_username: 
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Van Anthony S. Valencia" # Set default author name
      categories: "Places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
